version: "3"

services:

  download:
    image: ai-dw/db2:latest
    environment:
      - CREDUSER=${CREDUSER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DB=${DB_DB}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_TABLE=${DB_TABLE}
      - SALT=${SALT}
      - RTE=${RTE}
      - PROFILENAME=${PROFILENAME}
      - BUCKET=${BUCKET}
      - MODULE=${MODULE}
      - TF_SKIP_PROVIDER_VERIFY=1
      - TF_DATA_DIR=/work/.terraform
    volumes:
      - workdir:/work
      - cfgdir:/.projenv

volumes:
  cfgdir:
    driver_opts:
      device: $HOME/.projenv
      o: bind
       
workdir:
  driver_opts:
    device: $PWD
    o: bind

