version: "3"

services:

  upload:
    image: ai-dw/psql:latest-tg
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DB=${DB_DB}
      - DB_USER=${DB_USER}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_TABLE=${DB_TABLE}
      - BUCKET=${BUCKET}
      - TF_SKIP_PROVIDER_VERIFY=1
      - TF_DATA_DIR=/work/.terraform
    volumes:
      - workdir:/work
      - cfgdir:/root/.projenv

  mssql:
    image: ai-dw/mssql:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DB=${DB_DB}
      - DB_USER=${DB_USER}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_TABLE=${DB_TABLE}
      - BUCKET=${BUCKET}
      - TF_SKIP_PROVIDER_VERIFY=1
      - TF_DATA_DIR=/work/.terraform
    volumes:
      - workdir:/work
      - cfgdir:/root/.projenv


volumes:
  cfgdir:
    driver_opts:
      device: $HOME/.projenv
      o: bind
       
  workdir:
    driver_opts:
      device: $PWD
      o: bind

