version: "3"

services:

  dwhgen:
    build:
      context: .
      dockerfile: Dockerfile.dwhgen
    environment:
      - TF_SKIP_PROVIDER_VERIFY=1
      - TF_DATA_DIR=/work/.terraform
    volumes:
      - workdir:/work

  mssql:
    build:
      context: .
      dockerfile: Dockerfile.mssql

  postgres: 
    build:
      context: .
      dockerfile: Dockerfile.psql

  db2:
    build: 
      context: .
      dockerfile: Dockerfile.db2
    environment:
      - DB2_COMMAND='select 1'
    
  flyway:
    build:
      context: .
      dockerfile: Dockerfile.flyway

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform

volumes:
  workdir:
    driver_opts:
      device: $PWD
      o: bind

