FROM mcr.microsoft.com/mssql-tools

RUN apt-get update && apt-get install -y parallel pass python python-pip pigz && rm -rf /var/lib/apt/lists/*
RUN pip install s3cmd==2.0.2
ADD mssql_up.sh /bin/
ADD mssql_exec /bin/
RUN chmod 755 /bin/mssql_up.sh
RUN chmod 755 /bin/mssql_exec
ENV PATH "$PATH:/opt/mssql-tools/bin"
CMD ["/bin/mssql_exec"]
