FROM python:3.7.4-slim-stretch

RUN apt-get update && apt-get install -y parallel pass curl && rm -rf /var/lib/apt/lists/*
RUN curl -L -o /usr/local/bin/aws-vault https://github.com/99designs/aws-vault/releases/download/v4.6.4/aws-vault-linux-amd64
RUN chmod 755 /usr/local/bin/aws-vault
RUN export AWS_VAULT_BACKEND="pass"
RUN echo 'export AWS_VAULT_BACKEND="pass"' >> ~/.bashrc
RUN pip install dbt==0.14.0
RUN pip install s3cmd==2.0.2
