#!/bin/sh

[ -z "$SALT" ] && {  echo "SALT not found in environemnt" 1>&2 ; exit 1 ; }

echo ${RTE}\t${PROFILENAME}
echo USER?
read CREDUSER
echo PWD?
read CREDPWD
NPWD="${RTE}\t${PROFILENAME}\t${CREDUSER}\t${CREDPWD}"
echo $NPWD
echo $NPWD | /projbin/enc > "${SALT}.new"



