#!/bin/sh

[ -z "$SALT" ] && {  echo "SALT not found in environemnt" 1>&2 ; exit 1 ; }

# OLD_CRED_LINE=$(s3cmd get s3://$BUCKET/$SALT - | /projbin/dec.sh $SALT | grep ${RTE}\:${PROFILENAME})
NEW_CRED_LINE="$RTE\t$PROFILENAME\t$CREDUSER\t$CREDPWD"


{ s3cmd get s3://${BUCKET}/${SALT} - | /projbin/dec ${SALT} | grep -v -P "$RTE\t$PROFILENAME" ;  echo $NEW_CRED_LINE ; } | /projbin/enc | s3cmd put - s3://${BUCKET}/${SALT} 

